### ISSUE TITLE
Relative paths in settings.json?

### ISSUE THREAD

**Issue by zacjordaan** [yzane/vscode-markdown-pdf#1]
Before anything else, seriously well done on this project - it's great work!

I just wanted to know if it's possible to have settings.json accept _relative_ paths for the markdown-pdf.styles?

Something like this: 
`
    "markdown-pdf.styles": [
        ".vscode/md.css"
    ]
`

**Comment by yzane** [comment]
Relative paths are not currently supported, but I will try to support in a future release.

**Comment by yzane** [comment]
Released 0.1.5 with this fix.
Please update!
