### ISSUE TITLE
Text is reversed when I copy from a PDF

### ISSUE THREAD

**Issue by viktorbijlenga** [yzane/vscode-markdown-pdf#100]
First of all thanks for this excellent extension. It's great! I have one issue though. When I copy text from Preview.app (10.0) on Mac OS (10.13.6) all text is reversed. 

<img src="https://share.imwithfriends.se/heIxJ8mpVn/Screen-Recording-2018-08-16-14-22-14.gif">

Any ideas on why this is happening?

**Comment by viktorbijlenga** [comment]
I've found the issue. It seems to be related to the font-family I was using. Strange error.

**Comment by JipSogeti** [comment]
Which font-family did you use to resolve the issue? My text is also reversed when copying from Preview app on macOS 11.6.4.

**Comment by viktorbijlenga** [comment]
I think I used a system font stack in my css to resolve this.
https://css-tricks.com/snippets/css/system-font-stack/

**Comment by JipSogeti** [comment]
Great tip about the fonts :) Using arial and times to work around this issue.

**Comment by trinketmage** [comment]
The error is only reproductible with MacOS finder preview for PDF and it is related to variable fonts.
In my case it was with Mulish font https://fonts.google.com/specimen/Mulish.
I downloaded the source.ttf and included the non variable version to make it work properly.
