### ISSUE TITLE
provide more themes

### ISSUE THREAD

**Issue by IIInsomnia** [yzane/vscode-markdown-pdf#111]

**Comment by vimtaai** [comment]
You can use MDSS (https://github.com/vimtaai/mdss) to format your Markdown documents. It is a highly customizable CSS library designed for Markdown documents. You can use it out-of-the-box via CDN (https://cdn.jsdelivr.net/npm/mdss) or customize it to your liking: see README.

**Comment by IIInsomnia** [comment]
OK, thanks a lot !
