### ISSUE TITLE
support configuration of plantUML server

### ISSUE THREAD

**Issue by FrVaBe** [yzane/vscode-markdown-pdf#139]
Markdown PDF works great but it seems to always use the default plantUML server configured in [markdown-it-plantuml](https://github.com/gmunguia/markdown-it-plantuml). This server only accepts a certain number of requests per document. In documents with a large number of diagrams, not all diagrams are created. Instead, we have this warning in the document:

![grafik](https://user-images.githubusercontent.com/1521569/61377348-4e66b400-a8a3-11e9-84d7-82f7b3de1025.png)

The use of an own (local) PlantUML server usually helps here. Therefore this is a feature request to make the Plant UML Server address configurable.

See also a [corresponding Issue #12](https://github.com/gmunguia/markdown-it-plantuml/issues/12) in the _markdown-it-plantuml_ repository, but I think it is missplaced there and belongs to this project here.

**Comment by yzane** [comment]
Please upgrade Markdown PDF to ver1.4.4 and try.

**Comment by FrVaBe** [comment]
Thanks @yzane - that works just fine now!

Still looking for a possibility to have a nice preview in VS Code. Even the Markdown Preview Enhanced Plugin does not manage to show plantuml diagrams which are simple given as `@startuml ... @enduml` code snippets. And the output of the preview looks very different to the pdf output. Thus this is no alternative for me. But that is another story
