### ISSUE TITLE
Can't include images that contains "#" in the local path

### ISSUE THREAD

**Issue by kurehajime** [yzane/vscode-markdown-pdf#14]
Can't include images that contains "#" in the local path.

ex:

sample.md

    ![IMG](IMG.png)

|Result |Path |
|---|---|
|OK  |D:\CSharp\sample.md  |
|NG  |D:\C#\sample.md  |

---

>Markdown PDF 0.1.6

>version 1.9.1  
commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519  
date 2017-02-09T00:26:45.394Z  
shell 1.4.6  
render 53.0.2785.143  
Node 6.5.0

**Comment by yzane** [comment]
@kurehajime  Thank you for the report.
