### ISSUE TITLE
The font size of final pdf depends on display scaling (win10)

### ISSUE THREAD

**Issue by mst128256** [yzane/vscode-markdown-pdf#15]
VSCode 1.9.1
markdown-pdf 0.1.6
platform: win10, OS X

I observe too small font in pdf generated on machine with HighDPI display. It would be fine to have some display- and system-independent settings for font size.

### How to repoduce (win10)
1) take arbitrary non-empty .md document
2) in Preferences/System change magnification ration ("Change the size of text, apps, and other items")
3) generate pdf in VSCode
4) repeat 2-3 for different settings
5) compare pdfs

**Comment by yzane** [comment]
@mst128256 Thank you for the report.

**Comment by iamdevlinph** [comment]
Any update on this?

No idea for any other way to change font size of the generated PDF.

**Comment by cilerler** [comment]
I believe this should maked as **bug** since it does not allow us to use the extension.

**Comment by thomasaarholt** [comment]
I'm also facing this issue, on Windows. The body text comes out with a font size of about 9-10, which is really to small to read.

**Comment by maksymov** [comment]
same problem on ubuntu. maybe the problem is in phantomjs?

**Comment by cblomart** [comment]
+1

**Comment by jsalwen** [comment]
+1

**Comment by yzane** [comment]
I pre-released [Markdown PDF ver1.0.0](https://github.com/yzane/vscode-markdown-pdf/tree/release/1.0.0) which replaced pdf converter with puppeteer instead of html-pdf.
Please download from [here](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.0) and try.
Try using the markdown-pdf.scale option.
