### ISSUE TITLE
where the location that bundled Chromium installed?

### ISSUE THREAD

**Issue by amaothree** [yzane/vscode-markdown-pdf#150]
I use the chromium in my system by setting the config and I want to delete the bundled one. Where can I find it?

**Comment by gbdsantos** [comment]
if you are on Linux used this command on your terminal:
```Shell
whereis chromium
```

**Comment by amaothree** [comment]
> if you are on Linux used this command on your terminal:
> 
> ```shell
> whereis chromium
> ```

No, I know that and `where` command just can found the bin that installed by the package manager.  My question is where is "that chromium" that installed by the extension.

**Comment by yzane** [comment]
Delete the following directory:

Linux
`~/.vscode/extensions/yzane.markdown-pdf-x.x.x/node_modules/puppeteer/.local-chromium/`

Windows
`%USERPROFILE%\.vscode\extensions\yzane.markdown-pdf-x.x.x\node_modules\puppeteer\.local-chromium\`

**Comment by amaothree** [comment]
> Delete the following directory:
> 
> Linux
> `~/.vscode/extensions/yzane.markdown-pdf-x.x.x/node_modules/puppeteer/.local-chromium/`
> 
> Windows
> `%USERPROFILE%\.vscode\extensions\yzane.markdown-pdf-x.x.x\node_modules\puppeteer\.local-chromium\`

Thanks.
