### ISSUE TITLE
TOC: duplicated anchors won't work

### ISSUE THREAD

**Issue by pedroprates** [yzane/vscode-markdown-pdf#155]
The table of contents won't differentiate duplicated headers when creating anchors. For example, the VSCode Markdown Preview already [deals with it](https://github.com/microsoft/vscode/issues/47537) by appending a counter `-x` by the end of the anchor (updating the `href` and `id` on a HTML page). 

For demonstration purpose I've created [a markdown example](https://gist.github.com/pedroprates/35769fb5ca70be6465e0c79882ed0aae) covering this. This issue happens when I export both on HTML or PDF using Markdown PDF (and you can see this works as expected on Github): 

The second **Introduction** header link does not work, it's not clickable (on PDF) or it doesn't move to anywhere (HTML). I was thinking about why does this happen: probably because the anchor, `#introduction-1` is searching for a header like `Introduction 1`, just replacing every `-` for a blank character. For testing purposes, still on my example, I did 2 almost-equal section headers: **Another Method** and **Another Method 1**. The anchor of the latter header, `#another-method-1`, look-alike our duplicate anchor, and therefore the PDF (or HTML) looks for a header with the `1` by the end, like **Another Method 1**, also replacing the `-` for a blank character. On this second test, both PDF or HTML have worked well, so I think both files are looking exclusively replacing the `-` to a blank character. 

So, we need to begin to understand the anchors for duplicated headers, and since the *standard* seems to be add a `-x`, where `x` is a counter of how many times this header has appeared on the TOC, to the anchor name,  could we add this functionality here to PDF exports?

**Comment by LaryssaFernandes** [comment]
I have the same problem, but I need to generate a PDF.

**Comment by pedroprates** [comment]
The [VSCode-Markdown](https://github.com/yzhang-gh/vscode-markdown) package has it, but it doesn't have PDF support. I've seen that you guys are using [Markdown-it Named Headers](https://github.com/leff/markdown-it-named-headers) package to build the table of contents, and apparently they're not active (last commit made 4 years ago)... 

Well, as I've said the VSCode-Markdown package has support for duplicated anchors, and [this is the commit](https://github.com/yzhang-gh/vscode-markdown/commit/ffe43b5f7f3aea8d618e5e3bfe0405a98efbae5f) that they've added it.
