### ISSUE TITLE
"ReferenceError: MarkdownPdf is not defined" on auto create PDF on save in VSCodium

### ISSUE THREAD

**Issue by ubidev** [yzane/vscode-markdown-pdf#156]
Hi

Just switched from vscode to vscodium on multiple machines and am now getting 2 errors when auto creating pdfs on save while manual exporting to PDF works as expected:

- ReferenceError: MarkdownPdf is not defined
- ERROR: arkdownPdfOnSave()

![191027MarkdownPDFErrorsOnConvertOnSave](https://user-images.githubusercontent.com/14218601/67637904-84113500-f8b5-11e9-9d9e-882008ff85b1.png)

The only Markdown PDF parameter I use is: 

`"markdown-pdf.convertOnSave": true`

Setup Info:
- Markdown-PDF: 1.4.0
- VSCodium: 1.39.2
- Windows 10 Enterprise (winver) : 1903 - 18362.418

Thanks in advance
ubidev

**Comment by yzane** [comment]
Thank you for your report.

**Comment by ubidev** [comment]
No sweat 😓 don’t hesitate if I can be of any help

Envoyé de mon cerveau et d’un doigt...
Savoir Ubilogia
www.ubilogia.com
514-991-3438
________________________________
De : yzane <notifications@github.com>
Envoyé : Sunday, October 27, 2019 3:20:58 PM
À : yzane/vscode-markdown-pdf <vscode-markdown-pdf@noreply.github.com>
Cc : Georges VIVIER <gvivier@ubilogia.com>; Author <author@noreply.github.com>
Objet : Re: [yzane/vscode-markdown-pdf] "ReferenceError: MarkdownPdf is not defined" on auto create PDF on save in VSCodium (#156)


Thank you for your report.

**Comment by ubidev** [comment]
Wow! that was fast!
Just upgraded to 1.4.1 and I can confirm that the issue is fixed on my side!
Thanks a lot and have a great day!
ubidev :)
