### ISSUE TITLE
Enable glob / regexp filtering or ignore files?

### ISSUE THREAD

**Issue by HatiEth** [yzane/vscode-markdown-pdf#16]
I would like to request the ability to use globbing in the config to exclude other markdown files except the ones the globbing hits.

Alternatively I would be fine with a simple ignore files array inside of the configs. Maybe globbing could be enabled in that ignore later?

Note: This feature would be extremely useful with in conjunction with `convertOnSave`

**Comment by yzane** [comment]
@HatiEth Thanks for the feedback!
I will consider how to deal with it.
