### ISSUE TITLE
Latex Code Not working

### ISSUE THREAD

**Issue by ShayekhBinIslam** [yzane/vscode-markdown-pdf#188]
Latex code is being converted literally.

**Comment by basavyr** [comment]
Yeah, I face the same issue. Tried with both "$ $" and "$$ $$".

**Comment by pivan321** [comment]
Same issue here. I cant see my equations or math, is there a way to solve this?

**Comment by ShayekhBinIslam** [comment]
old issue. https://github.com/yzane/vscode-markdown-pdf/issues/21
kindly take action
