### ISSUE TITLE
Replace info messages with statusbar messages.

### ISSUE THREAD

**Issue by Graloth** [yzane/vscode-markdown-pdf#19]
The extension sends an info message each time it generates a PDF, those are intended for users to do something about them (basically to give users important information).
Since the message sent if it is a successful save is one that really doesn't need the user to do anything, having it be a statusbar message would be much better. (Errors should remain as they are now though).

The reason I mention this is that I save my file quite often, so the info bar often obscures my tabs, making it **very** annoying.

**Comment by yzane** [comment]
@Graloth Thanks for the feedback!
That's right. I will consider how to deal with it.
