### ISSUE TITLE
ERROR: phantomjs binary does not exist

### ISSUE THREAD

**Issue by williewould** [yzane/vscode-markdown-pdf#2]
Trying to generate a pdf, and keep getting this error:
`ERROR: phantomjs binary does not exist: C:\Users\user_name\.vscode\extensions\yzane.markdown-pdf-0.1.4\node_modules\phantomjs-pre`
I have tried running the command several times, but still keep getting this error.

I can't actually open the .pdf it generates. Please excuse me if its a trivial problem - I am new to using VSC. I also installed Auto-open Markdown  packages. 

Thanks in advance.

**Comment by yzane** [comment]
With the Internet connected, please open the markdown file with vscode.
Then phantomjs binary will be installed.

**Comment by tarofurukawa** [comment]
I have same issue in my environment.

I got following error:

```
ERROR: phantomjs binary does not exist: /Users/USERNAME/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
```

but phantomjs pre-built binary is installed in:

```
/Users/USERNAME/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/bin/phantomjs
```

Please check again.

**Comment by yzane** [comment]
Thank you for your report.

The following file is not a binary file.
```
/Users/USERNAME/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/bin/phantomjs
```

Is there the following phantomjs binary file?
- Windows
  - `C:\Users\USERNAME\.vscode\extensions\yzane.markdown-pdf-0.1.4\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe`
- Linux
  - `~/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs`

**Comment by applee** [comment]
If phantomjs is found in lib or on PATH, it will not be re-copied to dir `~/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/lib/phantom/bin`. So I think you should just use `~/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/bin/phantomjs` instead [hear](https://github.com/yzane/vscode-markdown-pdf/blob/master/extension.js#L410), it will always work well.

**Comment by adison** [comment]
With the Internet connected, please open the markdown file with vscode.
Then phantomjs binary will be installed. 
--
The solution doesn't work for me.

**Comment by amiuhle** [comment]
Having the same problem, got it working by symlinking the phantomjs binary:

```bash
mkdir -p ~/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/lib/phantom/bin
ln -s ~/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/bin/phantomjs  ~/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt/lib/phantom/bin/
```

**Comment by eminsenay** [comment]
I also had the same problem. Downloading the latest phantomjs and pasting the exe under ```C:\Users\USERNAME\.vscode\extensions\yzane.markdown-pdf-0.1.4\node_modules\phantomjs-prebuilt\lib\phantom\bin\``` workaround solved the problem.

**Comment by nuomi1** [comment]
For macOS 10.12 (brew was installed):

``` bash
brew install phantomjs
cd ~/.vscode/extensions/yzane.markdown-pdf-0.1.4/node_modules/phantomjs-prebuilt
mkdir lib/phantom/bin
ln -s /usr/local/bin/phantomjs lib/phantom/bin/phantomjs
```

**Comment by yzane** [comment]
Thanks for report.
@applee I will check it.

**Comment by yzane** [comment]
Released 0.1.5 with this fix.
Please update!

**Comment by eminsenay** [comment]
Still getting the same error after uninstall/install:
ERROR: phantomjs binary does not exist: C:\Users\[usernamehere]\.vscode\extensions\yzane.markdown-pdf-0.1.5\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

**Comment by yzane** [comment]
@eminsenay Thanks for info.
Markdown-pdf will automatically download phantomjs.
In version 0.1.4, if phantomjs were found in PATH, an error occurred.
This problem was fixed in version 0.1.5.
However, it seems that an error has occurred due to other causes.

With this fix, if phantomjs is found in PATH it will be used.
Therefore, if an error occurs, please download and install phantomjs from [here](http://phantomjs.org/download.html) and set it to PATH.

**Comment by Amroll** [comment]
I got a same error after install when I used "Convert Markdown to PDF". but when I install Node.js and reload this ext. This error is fixed.
So, I think [here](https://github.com/yzane/vscode-markdown-pdf/blob/master/extension.js#L461) maybe has some problem.

Another method to resolve this error(just windows):
1. Download phantomjs from [here](http://phantomjs.org/download.html)
2. Extract (unzip) the content and copy the `bin` folder to 

> C:\Users[usernamehere].vscode\extensions\yzane.markdown-pdf-0.1.5\node_modules\phantomjs-prebuilt\lib\phantom
3. Restart vscode.

**Comment by deadlydog** [comment]
Same problem for me as well
```
ERROR: phantomjs binary does not exist: C:\Users\USERNAME\.vscode\extensions\yzane.markdown-pdf-0.1.6\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
```

**Comment by andyrdavidson** [comment]
Same problem for me as well. @Amroll solution works for me. Like @deadlydog the file already existed at the appropriate location.

**Comment by yzane** [comment]
Since the size limit of the extensions increased from 20 MB to 100 MB, we included phantomjs.exe for Windows in Markdown-PDF 0.1.7.
[Increase Extension Size Limit](https://code.visualstudio.com/updates/v1_11#_increase-extension-size-limit)

**Comment by marsdotpset** [comment]
I got a same error after install when I used "Convert Markdown to PDF". 

Error message is 
`ERROR: phantomjs binary does not exist: /Users/mars/.vscode/extensions/yzane.markdown-pdf-0.1.7/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe`
The last two path separator are '\\',  not '/'.

I can found this exe file under the right path, but the default permissions of `~/.vscode/extensions/yzane.markdown-pdf-0.1.7/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe` 
is -rw-r--r--, maybe it should be -rwxr-xr-x?

OS: OS X EI Caption
Markdown PDF: 0.1.7

**Comment by peiyaoli** [comment]
I met the same issue as @marsdotpset ,
OS: ubuntu16.04
Markdown PDF:0.1.7

**Comment by malk271** [comment]
Same issue on MacOSX. The pre-build phantomjs.exe executable is a Windows binary. Not usable by OSX or Linux.

**Comment by malk271** [comment]
Simplest workaround for OSX users, at least, is to install Node.js (https://nodejs.org/en/), then go into the extensions directory and rebuild phantomjs: 
```
cd $HOME/.vscode/extensions/yzane.markdown-pdf-0.1.7/node_modules/phantomjs-prebuilt
/usr/local/bin/node install.js
```

**Comment by Sway007** [comment]
For Mac
>brew install phantomjs

For Ubuntu
>apt install phantomjs

then restart vscode, problem solved

**Comment by angelok1** [comment]
@malk271's rebuilt suggestion worked for me on high sierra.

**Comment by yzane** [comment]
Markdown PDF ver1.0.0 replaced PDF converter with puppeteer instead of node-html-pdf.
Therefore PhantomJS is no longer used.
