### ISSUE TITLE
Define Multiple outputformats

### ISSUE THREAD

**Issue by gajanak** [yzane/vscode-markdown-pdf#20]
It would be nice if markdown-pdf.type  could be a list, to generate PDF & HTML files the same time.

Perhaps somethink like 
```javascript
{
"markdown-pdf.type": "pdf,html",
"markdown-pdf.type": ["pdf","html"],
}

**Comment by rizickus** [comment]
Highly desired feature!

**Comment by sir-gon** [comment]
Yep, this feature would be great :)

**Comment by yzane** [comment]
I pre-released [Markdown PDF ver1.0.0](https://github.com/yzane/vscode-markdown-pdf/tree/release/1.0.0) which replaced pdf converter with puppeteer instead of html-pdf.
Please download from [here](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.0) and try.
