### ISSUE TITLE
Phantom js problem on  Mac OS 

### ISSUE THREAD

**Issue by YLRong** [yzane/vscode-markdown-pdf#22]
I tried converting a markdown file on Mac OS and got the following information:

ERROR: phantomjs binary does not exist: /Users/Hahaha/.vscode/extensions/yzane.markdown-pdf-0.1.7/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe

Is there something wrong? Or does it only work on Windows?

**Comment by azixMcAze** [comment]
I had the same problem. Uninstalling and reinstalling the extension solved the problem

**Comment by jiaxw32** [comment]
i had the same problem.Uninstalling and reinstalling the extension doesn't work for me. Any one have other soultions.

**Comment by liangmingran** [comment]
i had the same problem.Uninstalling and reinstalling the extension doesn't work for me too.
macOS version : Sieaar 10.12.6 (16G29)
vscode version :  1.15.1 (1.15.1)

**Comment by plucury** [comment]
Had same problem too. Uninstalling and reinstalling didn't work too.

**Comment by terrillmoore** [comment]
Problem is that the string (quoted above) has Windows-style backslashes as directory separators, and the package includes a Windows executable (`phantomjs.exe`). This causes things not to work on anything but Windows.

> `ERROR: phantomjs binary does not exist: /Users/Hahaha/.vscode/extensions/yzane.markdown-pdf-0.1.7/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe`

It should be possible to rebuild on your system from source and workaround this, but the instructions for doing this are insufficient; or perhaps I don't have all the right versions of all the node.js things around on my system. In any case, I think that shipping the `.exe` form causes this package to be Windows-only, at least for now.

**Comment by giogt** [comment]
I just wanted to add that, as expected, on Linux (Linux Mint 18.2 Sonya) I have the same problem.

**Comment by DaveEveritt** [comment]
To help the developer and focus the issue specifically, I've made this into a very specific issue here: #52

**Comment by liangmingran** [comment]
hello,everybody. i had the same problem in my mac.
i try to install  Phantomjs ,and then the extension is ok.
if you want to install Phantomjs,follow steps 
1. install  node environment 
> use  [nvm](https://github.com/creationix/nvm) or use [node offical ](https://nodejs.org/en/)
2. use npm install Phantomjs  ```npm install phantomjs -g```

have a try to convert a md to pdf, it will  be success.

**Comment by yzane** [comment]
I pre-released [Markdown PDF ver1.0.0](https://github.com/yzane/vscode-markdown-pdf/tree/release/1.0.0) which replaced pdf converter with puppeteer instead of html-pdf.
Please download from [here](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.0) and try.

**Comment by csjune** [comment]
ver 1.0 works well on macOS High Sierra. Thank you @yzane !

**Comment by yzane** [comment]
Markdown PDF ver1.0.0 replaced PDF converter with puppeteer instead of node-html-pdf.
Therefore PhantomJS is no longer used.

**Comment by yzane** [comment]
@csjune Thank you for the report.
