### ISSUE TITLE
How can I put the picture in markdown-pdf.header.contents ?

### ISSUE THREAD

**Issue by ukrit-himakoon** [yzane/vscode-markdown-pdf#23]
I want to put some logo on the header on every pages.
Could you please give us the example?

PS. such a wonderful plugin! I could say!

**Comment by ulih5b5** [comment]
An example would be perfect.  I'm struggling with the same issue. Text works fine, but I'm not able to add an image.  There's no error message during conversion but also no image on the generated pdf, not even  the alternate image text.

**Comment by yzane** [comment]
Since the markdown-pdf.header.contents option is not used now, this issue closed.
