### ISSUE TITLE
Is it possible to insert page breaks?

### ISSUE THREAD

**Issue by sybaz** [yzane/vscode-markdown-pdf#25]
Is it possible to insert page breaks? If so how?  Thanks

**Comment by sybaz** [comment]
Just found an answer here:
https://stackoverflow.com/questions/22601053/pagebreak-in-markdown-while-creating-pdf#29642392

Inserting this where a page break is needed does the trick:

<div style="page-break-after: always;"></div>

**Comment by malys** [comment]
Yes, it's possible see my pull request  [example](https://github.com/yzane/vscode-markdown-pdf/pull/45/files#diff-498fa614842bcef596b933323572b203R167) #45

**Comment by hackslashdave** [comment]
When combining html and markdown it can go a bit weird. I have a two column setup and something that worked for me is this:

```
<div class="page"></div>
&zwj;
<h1>Insert Title Here</h1>
```
