### ISSUE TITLE
VSCode Preview now supports KaTex. Feature request for markdown-pdf

### ISSUE THREAD

**Issue by upyesp** [yzane/vscode-markdown-pdf#259]
Hi,

This is a feature request.  VSCode now supports [KaTex](https://code.visualstudio.com/updates/v1_58#_languages) in the Markdown Preview pane,

Please add KaTex support to markdown-pdf.

Thanks.

**Comment by carneeki** [comment]
My current process:

1. Export to HTML
1. Open file in browser
1. Print to PDF.

KaTeX would be amazing!

**Comment by upyesp** [comment]
I opened this, but it is a duplicate if #168
