### ISSUE TITLE
How to break page where images span pages ?

### ISSUE THREAD

**Issue by SeaDude** [yzane/vscode-markdown-pdf#279]
Hello,

How do I automatically insert a page break where images span pages?

**Example:**
- ![image](https://user-images.githubusercontent.com/8636973/152659572-57c93e31-e3ee-48cf-b7e8-545c4e0f9c12.png)
- The green bordered image is actually an HTML table with an image embedded in the `<td>`. 
- I need to break the page above this table (automatically)
- Can this be done using this extension?

**Comment by hackslashdave** [comment]
I had a few issues with combining html and md - try this:
'''
<div class="page"></div>
&zwj;
<table><tr><td><img src="https://media.istockphoto.com/photos/cat-world-picture-id1311993425?b=1&k=20&m=1311993425&s=170667a&w=0&h=vFvrS09vrSeKH_u2XZVmjuKeFiIEjTkwr9KQdyOfqvg="/></td><tr></table>
'''

**Comment by SeaDude** [comment]
I'm not exactly sure what you mean. 

**Here is the code shown in the screenshot above:**

```
5. Click the `Media` tab on left screen 
6. Click `Upload` then select a logo from your machine
7. Set the `Image` property of `imgLogo` to the filename that was just uploaded

<table>
    <tr>
        <td style="border: 5px solid; border-collapse: collapse; padding:0px; border-color: #27ad74;">  
            <img src="assets/images/test.png"/> 
        </td>
    </tr>
</table>
```

Are you saying to insert a `<div>` tag and add `&zwj` above the `<table>`?

**Comment by SeaDude** [comment]
Apparently, that is *exactly* what you were saying (:)) because it worked!

![image](https://user-images.githubusercontent.com/8636973/163249087-a226bc8b-83a5-48c3-8907-e582b0dd6e35.png)

![image](https://user-images.githubusercontent.com/8636973/163249281-cfb466fe-5e6b-4b73-86b5-ae328b3e00e7.png)

Could you elaborate on how it works?

Thank you

**Comment by SeaDude** [comment]
Interesting!

- I don't know what the significance of the `<div class="page"` is
- I now know [`&zwj;`](https://en.wikipedia.org/wiki/Zero-width_joiner) is an invisible Unicode char!

**Comment by hackslashdave** [comment]
Ah, in the documentation they tell you to use:

`<div class="page"/>`

But I found it needed the closing tag instead (</div>)

The &zwj; was after a bit of trial and error, &nbsp; gave an ugly space above the table so I looked into other "empty characters" to try and hack around that and discovered &zwj; myself - glad I could help
