### ISSUE TITLE
How do I specify a relative output directory?

### ISSUE THREAD

**Issue by jodoint** [yzane/vscode-markdown-pdf#29]
I can specify an absolute path but how do I specify a path relative to where the markdown file is located?

Great tool by the way. Awesome work!

**Comment by fujohnwang** [comment]
+1

**Comment by jjloneman** [comment]
I also have wanted to see this fixed for the past year. I use VSCode and this plugin to convert markdown to PDFs for taking notes at school, but I don't want it to output in the same directory as my markdown, I want it to go into something like './PDFs'. Please fix this.

**Comment by yzane** [comment]
Please upgrade to Markdown PDF ver1.0.3 and try it.
