### ISSUE TITLE
Page number start form a specific page

### ISSUE THREAD

**Issue by prantikv** [yzane/vscode-markdown-pdf#3]
The footer gives option to set page numbes as shown

`"markdown-pdf.footer.contents": "<div style=\"text-align: center; margin-top: 0.5cm;\">{{page}}/{{pages}}</div>"`

However the page number starts from the first page, I want to offset it and want the page numbering to begin on the 5th page

Is it possible to add such a feature?

**Comment by yzane** [comment]
Output of page numbers uses "html-pdf" module.
If "html-pdf" adds such a feature, I will try to support in a future release.
