### ISSUE TITLE
TOC extension not working on Convert Markdown to PDF

### ISSUE THREAD

**Issue by ezequias** [yzane/vscode-markdown-pdf#31]
I can't see links working on a generated pdf from  markdown to pdf extension. TOC extension is working on default markdown preview on VSCode.

- VSCode Version: 1.15.1
- OS Version: Windows 10

Steps to Reproduce:

1. Write a nice markdown text (with many #, ## and ###) 
2. Enable TOC on Markdown (with Markdown TOC extension)
3. Convert Markdown to PDF (with Markdown to PDF extension)

If you have any plans to solve this reporting please tell me.

**Comment by dio833** [comment]
Hello

I convert md to html file with `Markdown PDF` then trace html code.

I see the tag &lt;h1-6&gt; doesn't has ID attribute.  So  Anchors can't work.

Could you keep the ID attribute of `<h1-6>` tag ?

Thanks.

**Comment by ezequias** [comment]
@dio833 I didn't understand you. How did you convert md to html with Markdown PDF? Is it another extension? All my attributes are from h1 to h6 but I confess it has some spaces on links generated.

Would  be nice if the extension only could create a hyperlink only about the first word of the markdown ID.

**Comment by dio833** [comment]
@ezequias 
`>user setting` open youre user setting then  find `  "markdown-pdf.type"`.

You can choose output format. such as `  "markdown-pdf.type": "html",`.

In HTML source , all h1~h6 tags miss ID attribute. So *Markdown TOC* can't work well here.

You can add  `id`  into h1~h6 tags manually . or maybe @yzane can fix this issue.

**Comment by ezequias** [comment]
@dio833 nice tip. I like it! ;)

**Comment by coop333** [comment]
This is related to issue #6

**Comment by sorgel** [comment]
As I see, using ID attributes is not enough to fix issue: phantomjs doesn't work well with internal links: [ariya/phantomjs/issues/13959](https://github.com/ariya/phantomjs/issues/13959)

**Comment by yzane** [comment]
I pre-released [Markdown PDF ver1.0.0](https://github.com/yzane/vscode-markdown-pdf/tree/release/1.0.0) which replaced pdf converter with puppeteer instead of html-pdf.
Please download from [here](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.0) and try.
