### ISSUE TITLE
[Question] Is it possible to convert from cmd / terminal / script

### ISSUE THREAD

**Issue by MrStickyPiston** [yzane/vscode-markdown-pdf#327]
I have a python script that automatically collects some data and puts it into a md file, but now i need to find a good way to build it.

**Comment by AveiShriety** [comment]
does have any process?

**Comment by AveiShriety** [comment]
does have any progress?

**Comment by MrStickyPiston** [comment]
I used a npm module and that did the job

**Comment by AveiShriety** [comment]
已收到，冯唯一。

**Comment by MrStickyPiston** [comment]
> 已收到，冯唯一。

Sorry, can you speak english

**Comment by AveiShriety** [comment]
> Sorry, can you speak English
sorry, it was sent automatically.
And I wanna know what's the npm package?

**Comment by AveiShriety** [comment]
>Sorry, can you speak English

Sorry, it was sent automatically. And I wanna know what's the nom package?

**Comment by MrStickyPiston** [comment]
md-to-pdf (TypeScript)
