### ISSUE TITLE
Multiple Exports Formats?

### ISSUE THREAD

**Issue by wrrq** [yzane/vscode-markdown-pdf#34]
Hey,

I tried to export a markdown file to pdf and html but it failed with

    "markdown-pdf.type": "pdf, html"

Is it somehow possible to achieve this without switching the settings all the time?

Best regards

**Comment by yzane** [comment]
Duplicate of #20

**Comment by rizickus** [comment]
Is there any progress regarding this feature?

**Comment by yzane** [comment]
Closing as dupe of #20
