### ISSUE TITLE
[BUG] Custom PDF style not being used

### ISSUE THREAD

**Issue by peterschussheim** [yzane/vscode-markdown-pdf#35]
Hi,

I am trying to use a custom [stylesheet](https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css) but it does not work as expected.  I've saved the CSS into `~.vscode-insiders/markdown-pdf.css` and added `"markdown-pdf.styles": [".vscode-insiders/markdown-pdf.css"]` to my settings.  Am I doing something wrong?

Thanks
Peter

**Comment by yzane** [comment]
Please upgrade to Markdown PDF ver1.0.3 and try it.

**Comment by 1danielcoelho** [comment]
Still doesn't seem to work, even on 1.0.3. Even if the files are local.

If anybody else needs this immediately, you can just replace  `on C:\Users\<you>\.vscode\extensions\yzane.markdown-pdf-1.0.3\styles\markdown-pdf.css` with your own style :)

**Comment by yzane** [comment]
@1danielcoelho 
If you save the css file in `~/.vscode-insiders/markdown-pdf.css`, please set as follows.

```
"markdown-pdf.styles": [
  "~/.vscode-insiders/markdown-pdf.css"
]
```

**Comment by yzane** [comment]
@peterschussheim 
Excuse me. I was misunderstanding the problem.

`.markdown-body` does not apply.
`body` is applied.
