### ISSUE TITLE
Broken internal links

### ISSUE THREAD

**Issue by lorenzo-arena** [yzane/vscode-markdown-pdf#37]
Hi,
I can't manage to get internal links in the exported PDF, even if they works in VSCode Markdown Preview.

Is there a way to get them working?

I'm using VSCode v1.16.1 in Windows 10 and Markdown PDF v0.1.7

**Comment by rizickus** [comment]
Same problem here!

**Comment by devjb** [comment]
I notice that the links are all absolute links, pointing to the absolute file path. Klicking on a Link on Windows for example, Adobe acrobat reader reacts by throwing a security warning stating that the PDF file tries to start an application:

>The PDF tries to start the following application:

> file:///C:/Users/<user>/Documents/...../.../.../converted.pdf
> 
> Do you really want to proceed?

Even by clicking accept, the link is not followed.

**Comment by HephepTeam** [comment]
Same here, I use the html converter in addition with the pdf converter and links are broken for both, these are ToC links only.

**Comment by iamwyza** [comment]
Also have this problem.  The links are pointing at the auto-generated anchors for section headers.  Such as:

```md
[Thing](#appendix-a)
## Appendix A
```

These work in your normal Markdown, VS Code's Markdown Preview, Github, etc.

**Comment by yzane** [comment]
Closing as dupe of #31
