### ISSUE TITLE
Not correctly rendering  Windows 1252 encoding

### ISSUE THREAD

**Issue by joshbradfield** [yzane/vscode-markdown-pdf#39]
Not correctly rendering .md documents with  Windows 1252 encoding:

For example the following md
```
abcdefghijklmnopqrstuvwxyz
à ç é è ê û 
```
exports as : 
```
abcdefghijklmnopqrstuvwxyz 􀀠 􀀠 􀀠 􀀠 􀀠 􀀠
```
![image](https://user-images.githubusercontent.com/4537119/31553189-e9aeac2e-b039-11e7-97b3-497fd81db55f.png)

btw,  thanks for a great tool  :)

**Comment by joshbradfield** [comment]
Saving as UTF-8 will preserve accents, both in the md, and in the exported .PDF
There is no real need to use ANSI or Windows 1252 in the first place. (It's just the default encoding where I work)

**Comment by yzane** [comment]
Please upgrade to Markdown PDF ver1.0.3 and try it.
