### ISSUE TITLE
How to change font size of generated pdf

### ISSUE THREAD

**Issue by NLinh2911** [yzane/vscode-markdown-pdf#40]
I have been trying to change the font size. The size was too big. I have tried to change the `markdown.preview.fontSize` from 14 to 11 but the final pdf is not changed.

I don't see the settings for changing font size in mardown-pdf settings.

Any suggestion ??

**Comment by angelok1** [comment]
I know this isn't ideal, but you can edit the css that generates it... go to the extension and edit styles/markdown.css (https://github.com/yzane/vscode-markdown-pdf/blob/master/styles/markdown.css)

**Comment by anath2** [comment]
You can also create your own .css file, add the style for font size you want and then point to it in your settings.json file: 
    
    "markdown-pdf.styles": [
        "path/to/your/markdown.css"
    ]

**Comment by BlueM** [comment]
Remark: while the Readme says that relative paths work and also includes examples, I found that relative paths are silently ignored, while absolute paths for the very same files work. Observed with VSCode 1.22.2 on macOS 10.12.6

**Comment by yzane** [comment]
Please upgrade to Markdown PDF ver1.0.3 and try it.
