### ISSUE TITLE
First H1 header not recognized if file starts with UTF-8 BOM

### ISSUE THREAD

**Issue by sba923** [yzane/vscode-markdown-pdf#44]
If the .md file is encoded as "UTF-8 with BOM", then the extension doesn't correctly convert the first H1 header (see example).

[test.pdf](https://github.com/yzane/vscode-markdown-pdf/files/1509624/test.pdf)
[test.zip](https://github.com/yzane/vscode-markdown-pdf/files/1509628/test.zip)

The extension should be modified so that it ignores the BOM when parsing the file's contents.

**Comment by yzane** [comment]
Please upgrade to Markdown PDF ver1.0.3 and try it.

**Comment by sba923** [comment]
Indeed, can't repro anymore with v1.2.0. Thanks for the fix.
