### ISSUE TITLE
After export to pdf, all the HyperLink and A tag were disabled

### ISSUE THREAD

**Issue by Marksion08** [yzane/vscode-markdown-pdf#46]
Thank you very much for your excellent plugin at first!

I wonder if i cause one issue,  while finish my markdown doc, i try to export to pdf,  but found that all the HyperLink and A tag were disabled. Click it but no work.

If there somewhere i was missing, pls leave me tip, thank you!

Regards,
Marksion

**Comment by sundevila84a19** [comment]
The URL of the link for tag points to the tag in source .md file, not to the bookmark in the .pdf file.

**Comment by yzane** [comment]
It was supported by Markdown PDF version 1.0.0.
