### ISSUE TITLE
Support custom scripts that rendres images (mermaid)

### ISSUE THREAD

**Issue by cblomart** [yzane/vscode-markdown-pdf#51]
Hello,

Is it possible to support custom scripting that renders images.

I more specificaly do use mermaid in my markdowns that are nicely renderd in vscode by its extention:
https://github.com/vstirbu/vscode-mermaid-preview

I did open an issue with them also:
https://github.com/vstirbu/vscode-mermaid-preview/issues/47

Thanks

**Comment by cblomart** [comment]
See reaction of vstribu in opened issue.

**Comment by yzane** [comment]
Closing as dupe of #30
