### ISSUE TITLE
Image in table not shown in output pdf

### ISSUE THREAD

**Issue by zhutq** [yzane/vscode-markdown-pdf#56]
The markdown file is like following:
```
<img src="test.png">

| Image |
| --- |
|<img src="test.png">|
```
Preview in vscode:
![screenshot from 2018-02-10 15-19-47](https://user-images.githubusercontent.com/1166360/36059584-fbc0a710-0e75-11e8-83d8-caaa21c2d861.png)

But in generated pdf, only the first image (outside table) is rendered.
![screenshot from 2018-02-10 15-21-48](https://user-images.githubusercontent.com/1166360/36059589-2b3201b0-0e76-11e8-8e22-7fa9130db046.png)

I'm using vscode 1.19.1 and Markdown PDF 0.1.7.

Any help? Thank you very much!

**Comment by yzane** [comment]
I pre-released [Markdown PDF ver1.0.0](https://github.com/yzane/vscode-markdown-pdf/tree/release/1.0.0) which replaced pdf converter with puppeteer instead of html-pdf.
Please download from [here](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.0) and try.

**Comment by zhutq** [comment]
It's fixed. Thank you!
