### ISSUE TITLE
Support for lightweight diagrams (PlantUML)

### ISSUE THREAD

**Issue by arnauldvm** [yzane/vscode-markdown-pdf#60]
It would be nice to support PlantUML [1] Markdown extension [2] (like Markdown Preview does [3]).

[1] http://plantuml.com/
[2] https://github.com/mikitex70/plantuml-markdown
[3] https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml#user-content-markdown-integrating

**Comment by yzane** [comment]
@arnauldvm Please upgrade to Markdown PDF ver1.2.0 and try it

**Comment by nyue** [comment]
I am using Markdown PDF ver 1.2.0, the PlantUML shows up in VSCode preview but the exported PDF file does not contain the diagram, just the embedded code.

**Comment by PetrGasparik** [comment]
confirmed, does not work for me - the PlantUML is just the code

**Comment by sirrus** [comment]
Same here - works in Preview - Code in PDF

**Comment by macasas** [comment]
I'm trying to get either plantuml or nomnoml diagrams out into any kind of png or pdf.

Plantuml quote the following for embedding, but that doesn't render in the preview
```plantumlcode
  Does not render
```
```plantuml
  Does render
```

But neither result in the flowchart being exported into any markdown-to-pdf filetype.

Is there an expected date for this, or should I look elsewhere?  

Thanks
