### ISSUE TITLE
unc path don't seem to convert to pdf correctly

### ISSUE THREAD

**Issue by rudyvogt** [yzane/vscode-markdown-pdf#61]
as you can see it display correctly quote below:
> [\\\\server1\Production\Automation\heritage\source](file:////server1/Production/Automation/heritage/source)

but it display as follows in the pdf: \\\\server1\Production\Automation\heritage\source(file:////server1/Production/Automation/heritage/source)

**Comment by yzane** [comment]
Please specify as follows.
"file:" is unnecessary.
```
[\\\\server1\Production\Automation\heritage\source](//server1/Production/Automation/heritage/source)
```
