### ISSUE TITLE
Ability to ignore YAML front matter

### ISSUE THREAD

**Issue by sd-tim** [yzane/vscode-markdown-pdf#62]
I'm using this plugin in concert with VSNotes which allows the addition of YAML front matter to specify metadata for the file. When the file is exported these are rendered at the beginning of the PDF, but I'd prefer them to be ignored.

Is this possible with an existing setting, or would it be possible to add a setting to ignore YAML front matter?

I've had a quick go at a regex, here: https://regex101.com/r/C21N92/2

**Comment by yzane** [comment]
Currently frontmatter is not supported.
