### ISSUE TITLE
Error Delimiter

### ISSUE THREAD

**Issue by AdilXia** [yzane/vscode-markdown-pdf#63]
/home/XX/.vscode/extensions/yzane.markdown-pdf-0.1.7/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe
as you can see, it has error delimiter while convert to pdf

**Comment by yzane** [comment]
Markdown PDF ver1.0.0 replaced PDF converter with puppeteer instead of node-html-pdf.
Therefore PhantomJS is no longer used.
