### ISSUE TITLE
not all images not converted to pdf

### ISSUE THREAD

**Issue by jamesrgregg** [yzane/vscode-markdown-pdf#65]
I'm finding that only the first image in my pdf is converted successfully within my 3 page pdf. I have a total of 4 images.  I attempted to resize the images within the markdown but it did not work either.  When displayed within the markdown itself, there's no issue.  
Is there a size limit (500px) ?

**Comment by yzane** [comment]
I pre-released [Markdown PDF ver1.0.0](https://github.com/yzane/vscode-markdown-pdf/tree/release/1.0.0) which replaced pdf converter with puppeteer instead of html-pdf.
Please download from [here](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.0) and try.

**Comment by jamesrgregg** [comment]
The issue was in my end. I had the path set incorrectly for 3 of the images.
