### ISSUE TITLE
H1 headers not recognized

### ISSUE THREAD

**Issue by jmalarcon** [yzane/vscode-markdown-pdf#7]
Hi:

I've been experimenting with this extension and I'm having trouble to generate level 1 headers using the syntax:

```
# Header content
```

It simply doesn't recognize it and generates the text as is (with the hash shown) when I convert to PDF using the extension.

Are you experiencing this problem?

Thanks for your work!

**Comment by yzane** [comment]
Thanks for info.

**Comment by sba923** [comment]
I just faced the issue with BOMs and will open a new issue for this to get fixed.
