### ISSUE TITLE
command 'extension.markdown-pdf' not found

### ISSUE THREAD

**Issue by davidgreen99** [yzane/vscode-markdown-pdf#71]
When I try to convert a MD file I see the message 'command 'extension.markdown-pdf' not found'. What does it mean and how can I resolve it?

**Comment by yzane** [comment]
What version are you using?

**Comment by davidgreen99** [comment]
VSCode 1.22.2
Markdown PDF 0.1.8

I've worked around the issue by reinstalling VSCode, but it is a pain to do that and reinstall all my extensions again too.

**Comment by yzane** [comment]
@davidgreen99  Please upgrade to Markdown PDF ver1.0.2 or higher and try it.
