### ISSUE TITLE
can not convert pdf

### ISSUE THREAD

**Issue by SeongBrave** [yzane/vscode-markdown-pdf#76]
VSCode 1.22.2
Markdown PDF 1.0.1

when i selected Export(pdf),the result is:
![image](https://user-images.githubusercontent.com/10784393/39162063-41a73942-47a6-11e8-8081-2dfdbb96f1d0.png)

**Comment by yzane** [comment]
Please download [Markdown PDF ver1.0.2](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.2) and try it.

**Comment by bowserm** [comment]
I get this error when I try to install v1.0.2:

VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

I had v1.0.1 installed. I tried both installing this over my current version and uninstalling my previous version before running the vsix.

**Comment by bowserm** [comment]
Thanks. v1.0.2 worked for me.

**Comment by yzane** [comment]
@bowserm Thank you for the report.

**Comment by phantium** [comment]
1.0.2 does not work for me either.

**Comment by yzane** [comment]
Can you solve the problem with the following operation?

1. Set the `markdown-pdf.executablePath` option
    See the [README](https://github.com/yzane/vscode-markdown-pdf) for `markdown-pdf.executablePath` option setting

1. Restart the Visual Studio Code

**Comment by SeongBrave** [comment]
@yzane now it's ok, thanks

**Comment by yzane** [comment]
@SeongBrave Thank you for the report.

**Comment by chikarifujino** [comment]
I got the reason why it can not be converted to PDF.
If `#` was included in the file name, it was not converted to PDF and `_tmp.html` was left.
By deleting `#` in the file name, conversion to PDF was completed.
In that case, I can convert without specifying `markdown-pdf.executablePath`.

Thank you for your quick reply.
I love this tool 😄

**Comment by yzane** [comment]
@chikarifujino Thank you for the report.
I will check it.

**Comment by yzane** [comment]
Please upgrade to Markdown PDF ver1.0.3 and try it.

**Comment by chikarifujino** [comment]
ver1.0.3 worked for me. Thanks!

Even if the file name contains `#`, I can convert it to PDF.

**Comment by yzane** [comment]
@chikarifujino Thank you for the report.

**Comment by emy97** [comment]
> Can you solve the problem with the following operation?
> 
>     1. Set the `markdown-pdf.executablePath` option
>        See the [README](https://github.com/yzane/vscode-markdown-pdf) for `markdown-pdf.executablePath` option setting
> 
>     2. Restart the Visual Studio Code
Hi everyone, I'm novice can anyone help me with these steps, with screenshots?

**Comment by DagiPaulos** [comment]
when I use: 
<img width="1049" alt="Screenshot 2022-12-29 at 11 32 36" src="https://user-images.githubusercontent.com/24784115/209939067-f396ec2b-3b27-4cbc-b845-9aadf5b55006.png">
I am getting the following wired pdf file:
<img width="1151" alt="Screenshot 2022-12-29 at 11 31 42" src="https://user-images.githubusercontent.com/24784115/209939216-aecb925a-ea39-427b-a93a-f280c2708243.png">
I could not find an issue similar to this in Stackoverflow or other platforms. Can someone tell me what the issue is? Thanks :)
