### ISSUE TITLE
can not work with lastest VS Code version

### ISSUE THREAD

**Issue by zhiqunliu** [yzane/vscode-markdown-pdf#77]
**ERROR:**
Command failed: npm rebuild puppeteer
C:\Users\admin\.vscode\extensions\yzane.markdown-pdf-1.0.1\node_modules\puppeteer\install.js:80
let progressBar = null;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "puppeteer"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! puppeteer@1.3.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.3.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\admin\.vscode\extensions\yzane.markdown-pdf-1.0.1\npm-debug.log

**VS Code version:**
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by yzane** [comment]
Please download [Markdown PDF ver1.0.2](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.2) and try it.

**Comment by FereX98** [comment]
I've downloaded the latest version (1.0.2) but it still doesn't work. There's a notification saying "Installing Puppeteer" like forever. Tried downloading with ShadowSocks on but no luck.

**Comment by gitto01** [comment]
Same here (version 1.0.2). There's a notification saying "Installing Puppeteer" like forever.

**Comment by gitto01** [comment]
I apologize, please ignore my last comment. It takes a long time to install Puppeteer but it works. Sorry again.

**Comment by yzane** [comment]
If you do not resolve with Markdown PDF ver1.0.2 please do the following.

1. Set the `markdown-pdf.executablePath` option
    See the [README](https://github.com/yzane/vscode-markdown-pdf) for markdown-pdf.executablePath option setting

1. Restart the Visual Studio Code

**Comment by yzane** [comment]
If you do not resolve with Markdown PDF ver1.0.2 please do the following.

1. Set the `markdown-pdf.executablePath` option
    See the [README](https://github.com/yzane/vscode-markdown-pdf) for markdown-pdf.executablePath option setting

1. Restart the Visual Studio Code

**Comment by FereX98** [comment]
@yzane I followed your instructions, changed `markdown-pdf.executablePath` to the directory of my chrome browser executable, and it finally works! Thanks you very much.

**Comment by yzane** [comment]
@FereX98 Thank you for the report.

**Comment by neyangg** [comment]
I searched everywhere, however found no solution about setting the "markdown-pdf.executablePath" option on MAC, any one could help?
