### ISSUE TITLE
Japanese font is not good

### ISSUE THREAD

**Issue by chikarifujino** [yzane/vscode-markdown-pdf#79]
Ming style and Gothic type mixed in Japanese font.
Kanji is Mincho type, Katakana is Gothic type.
Currently, for the same reason as # 68, CSS is not valid, so I can not change this state.

OS: Win10
markdown-pdf: Ver1.0.2

**Comment by yzane** [comment]
Please upgrade to Markdown PDF ver1.0.3 and try it.

**Comment by chikarifujino** [comment]
ver1.0.3 works!
`markdown-pdf.styles` option works and I can change Japanese font.
Thanks.

I'll close this issue.

**Comment by yzane** [comment]
@chikarifujino Thank you for the report.
