### ISSUE TITLE
Failed to download Chromium!

### ISSUE THREAD

**Issue by ahmad-511** [yzane/vscode-markdown-pdf#80]
Hello there,

After automatic update to 1.0.1 (2018/04/21) or maybe 1.0.0 (2018/04/15)
1- I opened an .md file
2- Notification appeared saying
> [Markdown PDF] Installing Puppeteer ...

3- Notification appeared saying
> ERROR: Failed to download Chromium! If you are behind a proxy, set the http.proxy option to settings.json and restart Visual Studio Code

and I don't have any proxy settings

4- I opened vs-code developer tools and the following is logged
> ERROR: Failed to download Chromium! If you are behind a proxy, set the http.proxy option to settings.json and restart Visual Studio Code.
> /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2217

> Extension Host] ENOENT: no such file or directory, access 'C:\Users\Ahmad\\.vscode\extensions\yzane.markdown-pdf-1.0.3\node_modules\puppeteer\.local-chromium\win64-549031\chrome-win32\chrome.exe'
> /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260

After some investigations I figured out that the request to
`https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/549031/chrome-win32.zip` returns:
> Access denied.
> We're sorry, but this service is not available in your location

What I'm expecting is: a message tells that it's not available in my location before being automatically installed and breaking the older version

Regards

**Comment by ykeisuke** [comment]
@ahmad-511 Hi

I have like same problem using macOS.
(ja_JP: macOSを使って僕も似たような問題を抱えていたけど、この問題を回避できたよ。)

But sorry, I did not try using Windows.
(ja_JP: だけどごめん、僕はWindowsでは試してないんだ。)

And, Maybe this problem directly reasons is not `vscode-markdown-pdf`. Maybe!
(ja_JP: あと、これはvscode-markdown-pdfの直接的な問題じゃないみたい、たぶん！)

Work for me using macOS:
(ja_JP: macOSを使ったときに動いた)

1. I opened an .md file (same your report)

2. Notification appeared saying (Same your report)
Abbreviated.

3. Notification appeared saying (Same your report)

> and I don't have any proxy settings

I also don't have any proxy settings and can reach internet.

4. I opend terminal and change dicrectory to `/Users/{YOUR_USER_NAME}/.vscode/extensions/yzane.markdown-pdf-1.0.3`

5. Run following command and get error log ( ◞‸◟ )

```term
$ npm i puppeteer

> puppeteer@1.3.0 install /Users/{YOUR_USER_NAME}/.vscode/extensions/yzane.markdown-pdf-1.0.3/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r549031! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1060:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:639:8) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.3.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{YOUR_USER_NAME}/.npm/_logs/2018-05-01T02_27_04_038Z-debug.log
```

6. Try but does not work for me, change node and git configs ( ◞‸◟ )

Does not work for me:

```term
$ npm config set strict-ssl false
$ git config --global http.sslVerify false
```

7. Try and work for me, set `NODE_TLS_REJECT_UNAUTHORIZED` setting. ✌('ω'✌ )

```term
$ export NODE_TLS_REJECT_UNAUTHORIZED=0
```

8. Install the puppeteer

```
$ npm install puppeteer

> puppeteer@1.3.0 install /Users/{YOUR_USER_NAME}/.vscode/extensions/yzane.markdown-pdf-1.0.3/node_modules/puppeteer
> node install.js

Downloading Chromium r549031 - 76 Mb [====================] 100% 0.0s
Chromium downloaded to /Users/{YOUR_USER_NAME}/.vscode/extensions/yzane.markdown-pdf-1.0.3/node_modules/puppeteer/.local-chromium/mac-549031
+ puppeteer@1.3.0
added 3 packages in 181.71s
```

OK!, Workaround! ʕ > з < ʔ
Startup VS-Code without errors.

Hope this helps.

**Comment by ahmad-511** [comment]
Well, Thanks @ykeisuke for your workaround

I know it's not related directly to yzane.markdown-pdf extension and what I'm hoping is a better error message instead

anyways, my workaround on windows was to manually download chrome-win32.zip and extract it to:
`C:\Users\{Username}\.vscode\extensions\yzane.markdown-pdf-1.0.3\node_modules\puppeteer.local-chromium\win64-549031\chrome-win32`

I also didn't restart vs-code and it worked just fine

Regards

**Comment by yzane** [comment]
@ahmad-511 Thank you for the report

I could not display an error message when downloading Chromium.
Fix to display error message.
Please download [Markdown PDF ver1.0.4](https://github.com/yzane/vscode-markdown-pdf/releases/tag/1.0.4) and try it.
Please let me know the error message when the download failed.

**Comment by ahmad-511** [comment]
@yzane , Thanks for the fix

Once download is finished it shows 
> Successfully installed the extension. Reload to enable it.

When I open an .md file the following notifications appear
> [Markdown PDF] Installing Chromium ...

> ERROR: Failed to download Chromium! If you are behind a proxy, set the http.proxy option to settings.json and restart Visual Studio Code. See https://github.com/yzane/vscode-markdown-pdf#install

> Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/549031/chrome-win32.zip

Now at least It provides a hint that ` server returned code 403`

And here is the console log
```
[Extension Host] ENOENT: no such file or directory, access 'C:\Users\Ahmad\.vscode\extensions\yzane.markdown-pdf-1.0.4\node_modules\puppeteer\.local-chromium\win64-549031\chrome-win32\chrome.exe'
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2217

ERROR: Failed to download Chromium! If you are behind a proxy, set the http.proxy option to settings.json and restart Visual Studio Code. See https://github.com/yzane/vscode-markdown-pdf#install
e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2217
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2217

Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/549031/chrome-win32.zip
e.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2217
```

So unfortunately I need to download chrome-win32.zip every time the extension has an updated

**Notes:**
1- My manually installed chrome-win32.zip is uninstalled, it's maybe better if installer can check for existing version before removing it and trying to install a new one and fail after that
2- when I tried to Export to PDF I've got no indication that there is a problem with the current installation and the task can' be accomplished

Thanks again

**Comment by yzane** [comment]
@ahmad-511 Thank you for the report

Please use [markdown-pdf.executablePath](https://github.com/yzane/vscode-markdown-pdf#markdown-pdfexecutablepath) option.
See [Install](https://github.com/yzane/vscode-markdown-pdf#install)

**Comment by ahmad-511** [comment]
Great, I change the settings to point to my chrome executable and It works like a charm 😄 

I just saw this note about markdown-pdf.executablePath in the installation instructions and not sure if it was there before and I'm happy for that

Thank you very much

**Comment by yzane** [comment]
@ahmad-511 Thank you 😄

**Comment by JunFreeman** [comment]
My MacBook, please tell me how to configure the path

**Comment by Jeff-Tian** [comment]
> My MacBook, please tell me how to configure the path

    "markdown-pdf.executablePath":"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

See: https://github.com/yzane/vscode-markdown-pdf/issues/77#issuecomment-405535914

**Comment by ilmari99** [comment]
I sometimes get this error when I try to export a Markdown file to a .pdf file, BEFORE the extension has succesfully loaded Chromium.
So wait for the installation to finish before trying to export with the extension.
