### ISSUE TITLE
Meiryo font causing \ to show as ¥

### ISSUE THREAD

**Issue by BobSeu** [yzane/vscode-markdown-pdf#83]
The Meiryo font is causing my PDFs and HTML versions of my markdown file to show \ as ¥.  

Is it possible to move this further down the font-family?  

EDIT:  I saw I can override the font family using the markdown-pdf.styles setting.

**Comment by yzane** [comment]
As the default setting, change Meiryo to be added at the end.

**Comment by yzane** [comment]
Please upgrade Markdown PDF to ver1.4.4 and try.

**Comment by BobSeu** [comment]
I removed the font family override and the slashes are showing correctly.  Thanks for the help!
