### ISSUE TITLE
TypeError: Cannot read property 'newPage' of undefined

### ISSUE THREAD

**Issue by Emmabyrne36** [yzane/vscode-markdown-pdf#85]
When I try to convert my markdown file to PDF I keep getting this error:
![image](https://user-images.githubusercontent.com/22704727/40232262-fccbb82c-5a95-11e8-9b60-0564cfb1cd3d.png)

I have tried to save the file in many different folders to see if that would solve the issue. I have reinstalled the extension several times. 
Is this a bug with the extension or is there a way to fix this?

My steps were:

- Create new .md file
- Ctrl + SHIFT + P to open command palate
- Select Markdown PDF: Export (pdf)

This error seems to occur when I choose any of the options except export as html.

When I look in the folder it has converted my .md to a temp.html file which I can view in my browser but I would like to save my documents as PDF files directly and not have them as HTML files.

**Comment by Emmabyrne36** [comment]
A reboot of my PC seems to have done the trick. Very strange error but at least it is working again.

**Comment by alvitawa** [comment]
I have this issue too, a restart didn't fix the problem for me.

**Comment by carmel4a** [comment]
C'mon there's still the same bug. Why this is closed?

**Comment by strider99** [comment]
same issue. restart didn't fix it. @carmel4a  what should i set the executable path in user settings.

**Comment by carmel4a** [comment]
Depends on system witch you have. It should be terminal/PowerShell command to run Chrome/Chromium.
On linux I need something like this `"markdown-pdf.executablePath": "chromium",` (in `User Settings`).

**Comment by mehedi-shafi** [comment]
For arch who are using Google Chrome from AUR use 
"markdown-pdf.executablePath": "google-chrome-stable"

this seems to do the trick.

**Comment by orhanmaden** [comment]
I use brave browser on Windows and had to set it to the `brave.exe` like:
```
"markdown-pdf.executablePath": "C:\\Path\\To\\brave.exe"
```
