### ISSUE TITLE
issue about supporting for Chinese characters

### ISSUE THREAD

**Issue by hikigaya58** [yzane/vscode-markdown-pdf#88]
when a markdown file includes chinese characters,it looks like this in vscode built-in preview(with extension 'Markdown Preview Github Styling'):
![image](https://user-images.githubusercontent.com/25583714/40528353-57a3187a-6023-11e8-9aa1-064582478d27.png)
but after 'vscode-markdown-pdf' to pdf , it looks like this:
![image](https://user-images.githubusercontent.com/25583714/40528436-9cb9b87e-6023-11e8-9b5d-6d0edae0549c.png)
you can see some characters don't look like others,their font alter.
the encoding is utf-8, vscode is 1.23.1,markdown-pdf is 1.2.0,os is win 10 17134.

**Comment by Sunpeng1995** [comment]
I think it is because the default font family is not compatible. You can try to change it using css and settings.json.

Add this line to your settings.json:
`"markdown-pdf.styles": ["path/to/your.css"]`

in css file:
`body{font-family: "宋体"; font-size: 16px;}`

**Comment by hikigaya58** [comment]
> I think it is because the default font family is not compatible. You can try to change it using css and settings.json.
> 
> Add this line to your settings.json:
> `"markdown-pdf.styles": ["path/to/your.css"]`
> 
> in css file:
> `body{font-family: "宋体"; font-size: 16px;}`

Yes, your answer solves the problem. But I hope that the author can adapt to Chinese characters!

**Comment by XiaoboD** [comment]
Why are there two errors when I do as you said?
![image](https://user-images.githubusercontent.com/53137243/81753845-47222e00-94e7-11ea-9cf4-0df22ca90bfb.png)
