### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by elipriaulx** [yzane/vscode-markdown-pdf#95]
`<span class='date'></span>` used in the header template doesn't respect my system date format, and I can't see any way to override the format in the available options. 

MDY format is not the [default interpretation](https://en.wikipedia.org/wiki/Date_format_by_country) for most of the world, and month/day ambiguity is a huge issue.

**Comment by kmindi** [comment]
Per default it should use the [ISO 8601](https://en.wikipedia.org/w/index.php?title=ISO_8601&oldid=851138376) format: yyyy-mm-dd
